version: '1'
services:

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=zazaza
      - POSTGRES_DB=eeefff
      - POSTGRES_HOST=localhost
    ports:
      - 6666:5432
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
  